/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.controller;

import com.saburi.dataacess.ProjectDAO;
import com.saburi.model.Project;
import com.saburi.utils.FXUIUtils;
import static com.saburi.utils.FXUIUtils.browseDirectory;
import static com.saburi.utils.FXUIUtils.errorMessage;
import static com.saburi.utils.FXUIUtils.getInt;
import static com.saburi.utils.FXUIUtils.getText;
import static com.saburi.utils.FXUIUtils.message;
import static com.saburi.utils.FXUIUtils.validateIteger;
import java.net.URL;
import java.util.List;
import java.util.Optional;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

public class ProjectController extends EditController {

    @FXML
    private TextField txtProjectID;
    @FXML
    private TextField txtProjectName;
    @FXML
    private TextField txtCommonProjectID;
    @FXML
    private TextField txtEntityPackage;
    @FXML
    private TextField txtDBAccessPackage;
    @FXML
    private TextField txtContollerPackage;
    @FXML
    private TextField txtUtilPackage;
    @FXML
    private TextField txtEnumClass;
    @FXML
    private TextField txtObjectNameClass;
    @FXML
    private TextArea txaEntityFolder;
    @FXML
    private TextArea txaDBAcessFolder;
    @FXML
    private TextArea txaControllerFolde;
    @FXML
    private TextArea txaResourceFolder;

    @FXML
    private Button btnEntityFolder, btnDBAcessFolder, btnControllerFolder, btnResourceFolder;
    private final ProjectDAO oProjectDA = new ProjectDAO();

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        try {
            validateIteger(txtProjectID);
            validateIteger(txtCommonProjectID);
            txtProjectID.focusedProperty().addListener((ov, t, t1) -> {
                if (t) {
                    loadData();
                }

            });

            browseDirectory(btnEntityFolder, txaEntityFolder);
            browseDirectory(btnDBAcessFolder, txaDBAcessFolder);
            browseDirectory(btnControllerFolder, txaControllerFolde);
            browseDirectory(btnResourceFolder, txaResourceFolder);
            this.primaryKeyControl = txtProjectID;
            this.dbAccess = oProjectDA;
            //this.minSize = 360;
        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    @Override
    protected void save() {
        try {
            this.editSuccessful = false;
            int projectID = getInt(txtProjectID, "Project ID");
            String projectName = getText(txtProjectName, "Project Name");
            int commonProjectID = getInt(txtCommonProjectID, "Common Project ID");
            String entityPackage = getText(txtEntityPackage, "Entity Package");
            String dBAccessPackage = getText(txtDBAccessPackage, "DB Access Package");
            String contollerPackage = getText(txtContollerPackage, "Controller Package");
            String utilPackage = getText(txtUtilPackage, "Util Package");
            String enumClass = getText(txtEnumClass, "Enum Class");
            String objectNameClass = getText(txtObjectNameClass, "Object Name Class");
            String entityFolder = getText(txaEntityFolder, "Entity Folder");
            String dBAcessFolder = getText(txaDBAcessFolder, "DB Access Folder");
            String controllerFolde = getText(txaControllerFolde, "Controller Folder");
            String resourceFolder = getText(txaResourceFolder, "Resource Folder");

            Project project = new Project(projectID, projectName, commonProjectID, entityPackage, dBAccessPackage, contollerPackage, utilPackage, enumClass, objectNameClass, entityFolder, dBAcessFolder, controllerFolde, resourceFolder);
            ProjectDAO projectDAO = new ProjectDAO(project);
            projectDAO.save();
            this.dbAccess = projectDAO;
            message("Operation: " + btnSave.getText() + "ed Successfully");

            this.editSuccessful = true;
        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    protected void delete() {
//        try {
//            int projectID = getInt(txtProjectID, "Project ID");
//            ProjectDA projectDA = oProjectDA.get(projectID);
//            if (!warningOk("Confirm Delete", "You are about to delete a record with ID: " + projectID + " Are you sure you want to continue?", "Remember this action cannot be un done")) {
//                return;
//            }
//            if (projectDA.delete()) {
//                message("Deleted Successfully");
//                this.clear();
//            }
//        } catch (Exception e) {
//            errorMessage(e);
//        }
    }

    @Override
    public void loadData() {
        try {
            if (txtProjectID.getText().isBlank()) {
                clear();
                return;
            }
            int projectID = getInt(txtProjectID, "Project ID");
            List<Project> projects = oProjectDA.read();
            Optional<Project> optionalProject = projects.parallelStream().filter(p -> (p).getProjectID() == projectID)
                    .findFirst();
            if (optionalProject.isPresent()) {
                Project project = optionalProject.get();
                txtProjectID.setText(String.valueOf(project.getProjectID()));
                txtProjectName.setText(project.getProjectName());
                txtCommonProjectID.setText(String.valueOf(project.getCommonProjectID()));
                txtEntityPackage.setText(project.getEntityPackage());
                txtDBAccessPackage.setText(project.getDBAccessPackage());
                txtContollerPackage.setText(project.getContollerPackage());
                txtUtilPackage.setText(project.getUtilPackage());
                txtEnumClass.setText(project.getEnumClass());
                txtObjectNameClass.setText(project.getObjectNameClass());
                txaEntityFolder.setText(project.getEntityFolder());
                txaDBAcessFolder.setText(project.getDBAcessFolder());
                txaControllerFolde.setText(project.getControllerFolde());
                txaResourceFolder.setText(project.getResourceFolder());

            }

        } catch (Exception e) {
            errorMessage(e);
        }

    }

    private void clear() {
        txtProjectName.clear();
        txtCommonProjectID.clear();
        txtEntityPackage.clear();
        txtDBAccessPackage.clear();
        txtContollerPackage.clear();
        txtUtilPackage.clear();
        txtEnumClass.clear();
        txtObjectNameClass.clear();
        txaEntityFolder.clear();
        txaDBAcessFolder.clear();
        txaControllerFolde.clear();
        txaResourceFolder.clear();

    }

}
